### ISSUE TITLE
Highscores not showing highscores of custom deck

### ISSUE THREAD

**Issue by HassanHeydariNasab** [SecUSo/privacy-friendly-memo-game#6]
Hi
When I score a high score in custom deck, it doesn't show on the Highscores!

**Comment by Xrygramming** [comment]
Hi,

thanks for your feedback. The described behaviour is not a bug since it was defined that a highscore for a custom deck should not be displayed. 
If a highscore should be available in the "Highscore-View" the saveHighscore()-method in the [MemoActivity ](https://github.com/SecUSo/privacy-friendly-memo-game/blob/master/app/src/main/java/org/secuso/privacyfriendlymemory/ui/MemoActivity.java) must be changed (do not check for memory.isCustomDesign()).

**Comment by HassanHeydariNasab** [comment]
Isn't it a bug, it's a feature? :D

**Comment by Xrygramming** [comment]
.. must be judged by @Yonjuni  :)

**Comment by Yonjuni** [comment]
I have labelled it as a bug after reviewing some other games and the resulting inconsistency in our game. So, the inclusion of the highscore should be consistent or be explained to the user.

**Comment by Yonjuni** [comment]
Solved by https://github.com/SecUSo/privacy-friendly-memo-game/commit/bf85acdd1daa15bd776e422c5b2eb485646602f1
